server.port=8082
spring.application.name=health-monitor

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

app.kafka.topic.health-events=service-health-events
app.monitor.service-a-url=http://localhost:8081/actuator/health
app.monitor.service-a-name=service-a
app.monitor.interval-ms=10000

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
